language: python

python:
  - "3.6"
  - "nightly"

matrix:
  - python: "nightly"

install:
  - ./bootstrap.sh

script:
  - pre-commit run --all-files
  - pytest --cov weirb
  # test install
  - inv build
  - pip install --ignore-installed dist/*
  - pytest

after_success:
  - codecov
